#include "ui/icons.h"

#include <algorithm>
#include <cstring>

#include <GLFW/glfw3.h>
#include <imgui.h>

#define NANOSVG_IMPLEMENTATION
#define NANOSVGRAST_IMPLEMENTATION
#include <nanosvg.h>
#include <nanosvgrast.h>

namespace
{

// Generated by src/ui/CMakeLists.txt: const char* const icon_svgs[] = { R"svg(...)svg", ... };
#include "icons_data.inc"
static_assert(sizeof(icon_svgs) / sizeof(icon_svgs[0]) == static_cast<size_t>(Icon::Count));

constexpr int base_px = 16;

struct IconAtlas
{
    GLuint texture = 0;
    int cols = 0;
    int rows = 0;
};

IconAtlas g_atlas;

void icon_uv(Icon icon, ImVec2& uv0, ImVec2& uv1)
{
    if (g_atlas.cols == 0) // icons_init() not called (headless UI tests): draw an empty cell
    {
        uv0 = uv1 = ImVec2(0, 0);
        return;
    }
    const int i = static_cast<int>(icon);
    const float du = 1.0f / static_cast<float>(g_atlas.cols);
    const float dv = 1.0f / static_cast<float>(g_atlas.rows);
    uv0 = ImVec2(static_cast<float>(i % g_atlas.cols) * du, static_cast<float>(i / g_atlas.cols) * dv);
    uv1 = ImVec2(uv0.x + du, uv0.y + dv);
}

float icon_size(float size)
{
    return size > 0.0f ? size : ImGui::GetFontSize();
}

} // namespace

IconAtlasPixels icons_rasterize(int scale)
{
    constexpr int count = static_cast<int>(Icon::Count);
    constexpr int cols = 8;
    constexpr int rows = (count + cols - 1) / cols;

    IconAtlasPixels atlas;
    atlas.cell = base_px * scale;
    atlas.width = cols * atlas.cell;
    atlas.height = rows * atlas.cell;
    atlas.rgba.assign(static_cast<size_t>(atlas.width) * atlas.height * 4, 0);

    NSVGrasterizer* rast = nsvgCreateRasterizer();
    std::vector<uint8_t> glyph(static_cast<size_t>(atlas.cell) * atlas.cell * 4);
    for (int i = 0; i < count; ++i)
    {
        // nsvgParse tokenises in place, so it needs a writable copy.
        std::vector<char> text(icon_svgs[i], icon_svgs[i] + std::strlen(icon_svgs[i]) + 1);
        NSVGimage* image = nsvgParse(text.data(), "px", 96.0f);
        if (image == nullptr)
        {
            continue;
        }
        std::fill(glyph.begin(), glyph.end(), 0);
        const float fit = static_cast<float>(atlas.cell) / std::max(image->width, image->height);
        nsvgRasterize(rast, image, 0, 0, fit, glyph.data(), atlas.cell, atlas.cell, atlas.cell * 4);
        nsvgDelete(image);

        const int x0 = (i % cols) * atlas.cell;
        const int y0 = (i / cols) * atlas.cell;
        for (int y = 0; y < atlas.cell; ++y)
        {
            for (int x = 0; x < atlas.cell; ++x)
            {
                uint8_t* dst = &atlas.rgba[(static_cast<size_t>(y0 + y) * atlas.width + x0 + x) * 4];
                dst[0] = dst[1] = dst[2] = 255;
                dst[3] = glyph[(static_cast<size_t>(y) * atlas.cell + x) * 4 + 3];
            }
        }
    }
    nsvgDeleteRasterizer(rast);
    return atlas;
}

void icons_init(float dpi_scale)
{
    const IconAtlasPixels px = icons_rasterize(dpi_scale > 1.0f ? 2 : 1);
    g_atlas.cols = px.width / px.cell;
    g_atlas.rows = px.height / px.cell;

    glGenTextures(1, &g_atlas.texture);
    glBindTexture(GL_TEXTURE_2D, g_atlas.texture);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glPixelStorei(GL_UNPACK_ALIGNMENT, 1);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA8, px.width, px.height, 0, GL_RGBA, GL_UNSIGNED_BYTE, px.rgba.data());
    glBindTexture(GL_TEXTURE_2D, 0);
}

void icons_shutdown()
{
    glDeleteTextures(1, &g_atlas.texture);
    g_atlas = {};
}

void icon_image(Icon icon, float size)
{
    ImVec2 uv0;
    ImVec2 uv1;
    icon_uv(icon, uv0, uv1);
    const float s = icon_size(size);
    ImGui::ImageWithBg(static_cast<ImTextureID>(g_atlas.texture), ImVec2(s, s), uv0, uv1, ImVec4(0, 0, 0, 0),
                       ImGui::GetStyleColorVec4(ImGuiCol_Text));
}

bool icon_button(const char* id, Icon icon, float size)
{
    ImVec2 uv0;
    ImVec2 uv1;
    icon_uv(icon, uv0, uv1);
    const float s = icon_size(size);
    return ImGui::ImageButton(id, static_cast<ImTextureID>(g_atlas.texture), ImVec2(s, s), uv0, uv1,
                              ImVec4(0, 0, 0, 0), ImGui::GetStyleColorVec4(ImGuiCol_Text));
}

bool icon_text_button(const char* label, Icon icon)
{
    ImVec2 uv0;
    ImVec2 uv1;
    icon_uv(icon, uv0, uv1);
    const ImGuiStyle& style = ImGui::GetStyle();
    const float s = icon_size(0.0f);
    const ImVec2 pos = ImGui::GetCursorScreenPos();
    ImGui::PushID(label);
    const bool pressed = ImGui::Button("##icon_text", ImVec2(icon_text_button_width(label), 0.0f));
    ImGui::PopID();
    const ImU32 col = ImGui::GetColorU32(ImGuiCol_Text);
    const ImVec2 icon_pos(pos.x + style.FramePadding.x, pos.y + (ImGui::GetFrameHeight() - s) * 0.5f);
    ImDrawList* dl = ImGui::GetWindowDrawList();
    dl->AddImage(static_cast<ImTextureID>(g_atlas.texture), icon_pos, ImVec2(icon_pos.x + s, icon_pos.y + s), uv0, uv1, col);
    dl->AddText(ImVec2(icon_pos.x + s + style.ItemInnerSpacing.x, pos.y + style.FramePadding.y), col, label);
    return pressed;
}

float icon_text_button_width(const char* label)
{
    const ImGuiStyle& style = ImGui::GetStyle();
    return icon_size(0.0f) + style.ItemInnerSpacing.x + ImGui::CalcTextSize(label).x + style.FramePadding.x * 2.0f;
}

float button_width(const char* label)
{
    return ImGui::CalcTextSize(label, nullptr, true).x + ImGui::GetStyle().FramePadding.x * 2.0f;
}

void same_line_or_wrap(float next_width)
{
    ImGui::SameLine();
    if (ImGui::GetContentRegionAvail().x < next_width)
    {
        ImGui::NewLine(); // ends the line at its current height, the next item starts below
    }
}
