// DBC writer: what dbc_write() emits must read back through dbc_parse() into the same
// database, field by field. The sample text below is hand-written (not generated by the
// writer) and covers standard + extended ids, Intel + Motorola, signed/unsigned, a
// multiplexer with muxed signals, float32 via SIG_VALTYPE_, value tables, quotes inside
// comments and value names, units and senders. The Motorola start bits it contains are
// also looked for verbatim in the output: the writer has to undo the parser's conversion.

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

#include <filesystem>
#include <sstream>
#include <string>
#include <string_view>

#include "db/dbc/dbc_parser.h"
#include "db/dbc/dbc_writer.h"
#include "db/model/can_db.h"

namespace
{

constexpr std::string_view sample = R"(VERSION "1.0"

NS_ :
	CM_
	VAL_

BS_:

BU_: EngineECU BodyECU Gateway

BO_ 256 EngineData: 8 EngineECU
 SG_ EngineSpeed : 0|16@1+ (0.125,0) [0|8031.875] "rpm" BodyECU,Gateway
 SG_ EngineTemp : 23|8@0+ (1,-40) [-40|215] "degC" BodyECU
 SG_ Torque : 24|16@0- (0.5,-1000) [-1000|1000] "Nm" Gateway
 SG_ Flags : 56|4@1+ (1,0) [0|15] "" Gateway

BO_ 2566844926 ExtSensor: 8 BodyECU
 SG_ Pressure : 7|32@0- (1,0) [0|0] "kPa" Gateway
 SG_ Counter : 32|8@1+ (1,0) [0|255] "" Gateway

BO_ 512 MuxMsg: 8 Gateway
 SG_ Mode M : 0|4@1+ (1,0) [0|15] "" BodyECU
 SG_ ValueA m0 : 8|16@1- (0.01,0) [-327.68|327.67] "V" BodyECU
 SG_ ValueB m1 : 8|16@1+ (1,0) [0|65535] "" BodyECU
 SG_ ValueC m2 : 15|8@0+ (2,1) [1|511] "mA" BodyECU

CM_ BO_ 256 "Engine data, said the \"manual\"";
CM_ SG_ 256 EngineSpeed "Rotational speed; 0.125 rpm per bit";
CM_ SG_ 512 Mode "Selects \"ValueA\" or \"ValueB\"";

VAL_ 512 Mode 0 "A" 1 "B" 2 "C" 15 "Not \"set\"" ;
VAL_ 256 Flags 0 "Off" 1 "On" ;

SIG_VALTYPE_ 2566844926 Pressure : 1;
)";

[[nodiscard]] std::string write(const CanDb& db)
{
    std::ostringstream out;
    dbc_write(db, out);
    return out.str();
}

void check_equal(const CanDbSignal& a, const CanDbSignal& b)
{
    CAPTURE(a.name);
    CHECK(a.name == b.name);
    CHECK(a.start_bit == b.start_bit);
    CHECK(a.length == b.length);
    CHECK(a.is_unsigned == b.is_unsigned);
    CHECK(a.big_endian == b.big_endian);
    CHECK(a.value_type == b.value_type);
    CHECK(a.factor == b.factor);
    CHECK(a.offset == b.offset);
    CHECK(a.min == b.min);
    CHECK(a.max == b.max);
    CHECK(a.unit == b.unit);
    CHECK(a.is_muxer == b.is_muxer);
    CHECK(a.is_muxed == b.is_muxed);
    CHECK(a.mux_value == b.mux_value);
    CHECK(a.comment == b.comment);
    CHECK(a.value_table == b.value_table);
}

void check_equal(const CanDb& a, const CanDb& b)
{
    REQUIRE(a.messages.size() == b.messages.size());
    for (auto ia = a.messages.begin(), ib = b.messages.begin(); ia != a.messages.end(); ++ia, ++ib)
    {
        CAPTURE(ia->first);
        CHECK(ia->first == ib->first);
        const CanDbMessage& ma = ia->second;
        const CanDbMessage& mb = ib->second;
        CHECK(ma.name == mb.name);
        CHECK(ma.raw_id == mb.raw_id);
        CHECK(ma.dlc == mb.dlc);
        CHECK(ma.sender == mb.sender);
        CHECK(ma.comment == mb.comment);
        CHECK(ma.muxer == mb.muxer);
        REQUIRE(ma.signals.size() == mb.signals.size());
        for (size_t i = 0; i < ma.signals.size(); ++i)
        {
            check_equal(ma.signals[i], mb.signals[i]);
        }
    }
}

} // namespace

TEST_CASE("parse(write(parse(text))) equals parse(text)")
{
    CanDb first;
    REQUIRE(dbc_parse(sample, first));
    REQUIRE(first.messages.size() == 3);

    const std::string text = write(first);
    CAPTURE(text);
    CanDb second;
    std::vector<DbcError> errors;
    REQUIRE(dbc_parse(text, second, &errors));
    CHECK(errors.empty());
    check_equal(first, second);

    // Nothing was silently dropped on the way in: spot checks against the sample.
    const CanDbMessage* mux = can_db_find_message(second, 512);
    REQUIRE(mux != nullptr);
    CHECK(can_db_muxer(*mux) == can_db_find_signal(*mux, "Mode"));
    CHECK(can_db_find_signal(*mux, "Mode")->comment == "Selects \"ValueA\" or \"ValueB\"");
    CHECK(can_signal_value_name(*can_db_find_signal(*mux, "Mode"), 15) == "Not \"set\"");
    const CanDbMessage* ext = can_db_find_message(second, 2566844926u);
    REQUIRE(ext != nullptr);
    CHECK(can_db_find_signal(*ext, "Pressure")->value_type == SignalValueType::float32);
    CHECK(can_db_find_message(second, 256)->comment == "Engine data, said the \"manual\"");
}

// The emitted text itself, where the sample fixes what it must contain.
TEST_CASE("written text uses DBC conventions")
{
    CanDb db;
    REQUIRE(dbc_parse(sample, db));
    const std::string text = write(db);
    CAPTURE(text);

    CHECK(text.starts_with("VERSION \"\"\n"));
    CHECK(text.find("\nNS_ : \n\tNS_DESC_\n\tCM_\n") != std::string::npos);
    CHECK(text.find("\nBS_:\n") != std::string::npos);
    // Senders, unique, in first-seen (raw id) order: 256, 512, 2566844926.
    CHECK(text.find("\nBU_: EngineECU Gateway BodyECU\n") != std::string::npos);

    CHECK(text.find("\nBO_ 256 EngineData: 8 EngineECU\n") != std::string::npos);
    CHECK(text.find("\nBO_ 2566844926 ExtSensor: 8 BodyECU\n") != std::string::npos);
    // Messages in raw id order.
    CHECK(text.find("BO_ 256 ") < text.find("BO_ 512 "));
    CHECK(text.find("BO_ 512 ") < text.find("BO_ 2566844926 "));

    // Motorola start bits back in DBC sawtooth numbering, Intel unchanged.
    CHECK(text.find(" SG_ EngineSpeed : 0|16@1+ (0.125,0) [0|8031.875] \"rpm\" ") != std::string::npos);
    CHECK(text.find(" SG_ EngineTemp : 23|8@0+ (1,-40) [-40|215] \"degC\" ") != std::string::npos);
    CHECK(text.find(" SG_ Torque : 24|16@0- (0.5,-1000) [-1000|1000] \"Nm\" ") != std::string::npos);
    CHECK(text.find(" SG_ Pressure : 7|32@0- (1,0) [0|0] \"kPa\" ") != std::string::npos);
    CHECK(text.find(" SG_ Mode M : 0|4@1+ (1,0) [0|15] \"\" ") != std::string::npos);
    CHECK(text.find(" SG_ ValueA m0 : 8|16@1- (0.01,0) [-327.68|327.67] \"V\" ") != std::string::npos);
    CHECK(text.find(" SG_ ValueC m2 : 15|8@0+ (2,1) [1|511] \"mA\" ") != std::string::npos);

    CHECK(text.find("\nCM_ BO_ 256 \"Engine data, said the \\\"manual\\\"\";\n") != std::string::npos);
    CHECK(text.find("\nCM_ SG_ 256 EngineSpeed \"Rotational speed; 0.125 rpm per bit\";\n") != std::string::npos);
    CHECK(text.find("\nVAL_ 512 Mode 0 \"A\" 1 \"B\" 2 \"C\" 15 \"Not \\\"set\\\"\" ;\n") != std::string::npos);
    CHECK(text.find("\nVAL_ 256 Flags 0 \"Off\" 1 \"On\" ;\n") != std::string::npos);
    CHECK(text.find("\nSIG_VALTYPE_ 2566844926 Pressure : 1;\n") != std::string::npos);
    CHECK(text.find("SIG_VALTYPE_ 256 ") == std::string::npos);   // integer signals get none (2566844926 has one)
}

// Values the parser never produces itself: no sender, doubles that need an exponent,
// a float64 signal and a backslash in a comment.
TEST_CASE("hand-built database round trips")
{
    CanDb db;
    CanDbMessage& msg = db.messages[0x123];
    msg = CanDbMessage{.name = "Odd", .raw_id = 0x123, .dlc = 8};
    msg.signals.push_back(CanDbSignal{
        .name = "Tiny", .start_bit = 0, .length = 16, .is_unsigned = false, .factor = 1e-7, .offset = -2.5e20,
        .min = -1e300, .max = 1e300, .unit = "µV", .comment = "back\\slash and \"quote\""});
    msg.signals.push_back(CanDbSignal{
        .name = "Wide", .start_bit = 0, .length = 64, .big_endian = true, .value_type = SignalValueType::float64,
        .factor = 0.1, .offset = 0.3});

    const std::string text = write(db);
    CAPTURE(text);
    CHECK(text.find("BO_ 291 Odd: 8 Vector__XXX\n") != std::string::npos);
    CHECK(text.find("\nBU_:\n") != std::string::npos);
    CHECK(text.find(" SG_ Wide : 7|64@0- (0.1,0.3) [0|0] \"\" ") != std::string::npos);
    CHECK(text.find("SIG_VALTYPE_ 291 Wide : 2;") != std::string::npos);

    CanDb back;
    REQUIRE(dbc_parse(text, back));
    check_equal(db, back);
    const CanDbSignal* tiny = can_db_find_signal(back.messages[0x123], "Tiny");
    REQUIRE(tiny != nullptr);
    CHECK(tiny->factor == 1e-7);
    CHECK(tiny->offset == -2.5e20);
    CHECK(tiny->comment == "back\\slash and \"quote\"");
    CHECK(back.messages[0x123].sender.empty()); // Vector__XXX reads back as "no sender"
}

TEST_CASE("dbc_write_file writes a parseable file and reports open failures")
{
    CanDb db;
    REQUIRE(dbc_parse(sample, db));

    const auto path = std::filesystem::temp_directory_path() / "kraken_dbc_writer_test.dbc";
    std::string error;
    REQUIRE(dbc_write_file(db, path, &error));
    CHECK(error.empty());
    CanDb back;
    CHECK(dbc_parse_file(path, back));
    check_equal(db, back);
    std::filesystem::remove(path);

    const auto bad = std::filesystem::temp_directory_path() / "kraken_no_such_dir" / "x.dbc";
    CHECK_FALSE(dbc_write_file(db, bad, &error));
    CHECK_FALSE(error.empty());
    CHECK_FALSE(dbc_write_file(db, bad, nullptr));   // error pointer is optional
}
